### ISSUE TITLE
Does not compile on FreeBSD13.0

### ISSUE THREAD

**Issue by devosalain** [Firstbober/wapanel#28]

**Comment by Firstbober** [comment]
Can you tell me more about the problem, sir?
Compilation errors, etc.

**Comment by devosalain** [comment]
Offcourse. Sorry I did not provide the correct information.
In fact it compiles but crashes at running.

HOST:x: /home/x/wapanel/wapanel >mkdir build                                                                                                             0
HOST:x: /home/x/wapanel/wapanel >cd build                                                                                                                0
HOST:x: /home/x/wapanel/wapanel/build >meson ..                                                                                                          0
The Meson build system
Version: 0.58.1
Source dir: /usr/home/x/wapanel/wapanel
Build dir: /usr/home/x/wapanel/wapanel/build
Build type: native build
Project name: wapanel
Project version: 1.0.0
C++ compiler for the host machine: ccache c++ (clang 11.0.1 "FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)")
C++ linker for the host machine: c++ ld.lld 11.0.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
C compiler for the host machine: ccache cc (clang 11.0.1 "FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)")
C linker for the host machine: cc ld.lld 11.0.1
Library dl found: YES
Found pkg-config: /usr/local/bin/pkg-config (1.7.4)
Run-time dependency gtk-layer-shell-0 found: YES 0.6.0
Run-time dependency gtk+-3.0 found: YES 3.24.29
Run-time dependency gio-2.0 found: YES 2.66.8
Run-time dependency threads found: YES
Run-time dependency wayland-protocols found: YES 1.21
Run-time dependency wayland-client found: YES 1.19.0
Program wayland-scanner found: YES (/usr/local/bin/wayland-scanner)
Run-time dependency libpulse found: YES 14.2
Dependency threads found: YES unknown (cached)
Configuring config_data.hh using configuration
Build targets in project: 10

Found ninja-1.10.2 at /usr/local/bin/ninja
HOST:x: /home/x/wapanel/wapanel/build >ninja                                                                                                             0
[20/40] Compiling C++ object src/applets/app-finder/libwapanel-applet-app-finder.so.p/components_list_area.cc.o
In file included from ../src/applets/app-finder/components/list_area.cc:1:
../src/applets/app-finder/components/list_area.hh:37:7: warning: private field 'm_search_container_visible' is not used [-Wunused-private-field]
        bool m_search_container_visible = false;
             ^
1 warning generated.
[40/40] Linking target wapanel
HOST:x: /home/x/wapanel/wapanel/build >aa                                                                                                                0
build.ninja            config_data.hh          libwapanel-appletapi.a.p/  meson-logs/     meson-uninstalled/  thirdparty/  wapanel.p/
compile_commands.json  libwapanel-appletapi.a  meson-info/                meson-private/  src/                wapanel*     
HOST:x: /home/x/wapanel/wapanel/build >./wapanel                                                                                                         0
[wapanel] [INFO] (../src/main.cc:193): Started wapanel version 1.0.0
zsh: abort      ./wapanel
HOST:x: /home/x/wapanel/wapanel/build >                     
It ungracefully ends with abort while running.

**Comment by Firstbober** [comment]
Very weird, I will make a VM with FreeBSD and try to reproduce it.

**Comment by jbeich** [comment]
Works fine for me on [Sway snapshot](https://github.com/freebsd/freebsd-ports/compare/main...jbeich:wlroots-0.15). Maybe try [the port](https://www.freshports.org/x11/wapanel) I've just created.

**Comment by jbeich** [comment]
If you're launching `wapanel` from screen/tmux make sure `WAYLAND_DISPLAY` + `XDG_RUNTIME_DIR` [environment variables](https://man.freebsd.org/environ/7) which are used to find Wayland [Unix domain](https://man.freebsd.org/unix/4) socket are propagated from the terminal emulator.

**Comment by Firstbober** [comment]
Checked on GhostBSD VM, wapanel gets past config creation etc. but crashes due to being on x11 session. Try port mentioned above or compile it again. In short, can't reproduce it.

**Comment by devosalain** [comment]
The program ends with "abort trap".
# freebsd-version -kru                                                                                        0
13.0-RELEASE-p3
13.0-RELEASE-p3
13.0-RELEASE-p3

**Comment by jbeich** [comment]
Build the port `WITH_DEBUG=1` or this repo with `--buildtype debug` then run under lldb/gdb to get an idea why and where it crashes.

**Comment by jbeich** [comment]
In lldb/gdb don't forget to type `bt`, so it prints the whole trace and not just the tip that maybe in libc.

**Comment by jbeich** [comment]
For example, I can't reproduce inside FreeBSD 13.0 amd64 jail with Sway 1.6 and default config. To figure out whether this is a pilot error or an unhandled error condition you need to provide more details.

**Comment by jbeich** [comment]
Also works on FreeBSD under Wayfire 0.7.2. OTOH, labwc and hikari don't implement `wlr-foreign-toplevel-management` necessary to run wapanel.

**Comment by Firstbober** [comment]
It must crash in a very weird place before any config reading. As jbeich said, running wapanel with debugger is the only viable option. I'm really curious what makes it abort.
